import { NextResponse } from "next/server";
import prisma from "@/lib/db";

// GET /api/stats/business-totals - Get total business generated by each user type
export async function GET() {
  try {
    // Get total investment from purchase bills
    const purchaseBills = await prisma.purchaseBill.findMany({
      where: {
        status: { not: "cancelled" },
      },
      select: {
        totalAmount: true,
        paidAmount: true,
      },
    });

    const totalInvestment = purchaseBills.reduce(
      (sum, bill) => sum + bill.totalAmount,
      0
    );
    const paidInvestment = purchaseBills.reduce(
      (sum, bill) => sum + bill.paidAmount,
      0
    );

    // Get stock value (costPrice * stockQuantity for all products)
    const products = await prisma.product.findMany({
      where: {
        status: "in_stock",
      },
      select: {
        costPrice: true,
        stockQuantity: true,
        retailPrice: true,
      },
    });

    const stockValue = products.reduce(
      (sum, product) => sum + (product.costPrice * product.stockQuantity),
      0
    );

    const stockRetailValue = products.reduce(
      (sum, product) => sum + (product.retailPrice * product.stockQuantity),
      0
    );

    const totalStockQuantity = products.reduce(
      (sum, product) => sum + product.stockQuantity,
      0
    );

    // Get wholesaler business totals
    const wholesaleOrders = await prisma.wholesaleOrderBill.findMany({
      where: {
        status: { not: "cancelled" },
      },
      select: {
        grandTotal: true,
        status: true,
      },
    });

    const wholesaleTotalBusiness = wholesaleOrders.reduce(
      (sum, order) => sum + order.grandTotal,
      0
    );
    const wholesalePaidBusiness = wholesaleOrders
      .filter((o) => o.status === "paid")
      .reduce((sum, order) => sum + order.grandTotal, 0);
    const wholesaleOrderCount = wholesaleOrders.length;

    // Get reseller business totals
    const resellerOrders = await prisma.orderBill.findMany({
      where: {
        status: { not: "cancelled" },
      },
      select: {
        grandTotal: true,
        status: true,
      },
    });

    const resellerTotalBusiness = resellerOrders.reduce(
      (sum, order) => sum + order.grandTotal,
      0
    );
    const resellerPaidBusiness = resellerOrders
      .filter((o) => o.status === "paid")
      .reduce((sum, order) => sum + order.grandTotal, 0);
    const resellerOrderCount = resellerOrders.length;

    // Get retail business totals
    const retailOrders = await prisma.retailOrderBill.findMany({
      where: {
        status: { not: "cancelled" },
      },
      select: {
        grandTotal: true,
        status: true,
      },
    });

    const retailTotalBusiness = retailOrders.reduce(
      (sum, order) => sum + order.grandTotal,
      0
    );
    const retailPaidBusiness = retailOrders
      .filter((o) => o.status === "paid")
      .reduce((sum, order) => sum + order.grandTotal, 0);
    const retailOrderCount = retailOrders.length;

    const totalSales = wholesaleTotalBusiness + resellerTotalBusiness + retailTotalBusiness;

    return NextResponse.json({
      wholesaler: {
        totalBusiness: wholesaleTotalBusiness,
        paidBusiness: wholesalePaidBusiness,
        orderCount: wholesaleOrderCount,
      },
      reseller: {
        totalBusiness: resellerTotalBusiness,
        paidBusiness: resellerPaidBusiness,
        orderCount: resellerOrderCount,
      },
      retail: {
        totalBusiness: retailTotalBusiness,
        paidBusiness: retailPaidBusiness,
        orderCount: retailOrderCount,
      },
      grandTotal: totalSales,
      // New investment & stock stats
      investment: {
        total: totalInvestment,
        paid: paidInvestment,
        pending: totalInvestment - paidInvestment,
        billCount: purchaseBills.length,
      },
      stock: {
        costValue: stockValue,
        retailValue: stockRetailValue,
        quantity: totalStockQuantity,
        potentialProfit: stockRetailValue - stockValue,
      },
      totalSales,
    });
  } catch (error) {
    console.error("Error fetching business totals:", error);
    return NextResponse.json(
      { error: "Failed to fetch business totals" },
      { status: 500 }
    );
  }
}
