import { NextResponse } from "next/server";
import prisma from "@/lib/db";

// GET /api/stats/business-totals - Get total business generated by each user type
// OPTIMIZED: Uses Promise.all for parallel queries + DB aggregation instead of JS reduce
export async function GET() {
  try {
    // Execute ALL queries in parallel using Promise.all
    const [
      // Purchase bill aggregation
      purchaseStats,
      purchaseBillCount,
      // Product stock values (need raw query for computed fields)
      products,
      // Wholesale order aggregations
      wholesaleTotalStats,
      wholesalePaidStats,
      wholesaleOrderCount,
      // Reseller order aggregations
      resellerTotalStats,
      resellerPaidStats,
      resellerOrderCount,
      // Retail order aggregations
      retailTotalStats,
      retailPaidStats,
      retailOrderCount,
    ] = await Promise.all([
      // Purchase bills - aggregate totals
      prisma.purchaseBill.aggregate({
        where: { status: { not: "cancelled" } },
        _sum: { totalAmount: true, paidAmount: true },
      }),
      prisma.purchaseBill.count({
        where: { status: { not: "cancelled" } },
      }),
      // Products - need individual fields for computed stock value
      prisma.product.findMany({
        where: { status: "in_stock" },
        select: { costPrice: true, stockQuantity: true, retailPrice: true },
      }),
      // Wholesale orders - total business
      prisma.wholesaleOrderBill.aggregate({
        where: { status: { not: "cancelled" } },
        _sum: { grandTotal: true },
      }),
      // Wholesale orders - paid only
      prisma.wholesaleOrderBill.aggregate({
        where: { status: "paid" },
        _sum: { grandTotal: true },
      }),
      prisma.wholesaleOrderBill.count({
        where: { status: { not: "cancelled" } },
      }),
      // Reseller orders - total business
      prisma.orderBill.aggregate({
        where: { status: { not: "cancelled" } },
        _sum: { grandTotal: true },
      }),
      // Reseller orders - paid only
      prisma.orderBill.aggregate({
        where: { status: "paid" },
        _sum: { grandTotal: true },
      }),
      prisma.orderBill.count({
        where: { status: { not: "cancelled" } },
      }),
      // Retail orders - total business
      prisma.retailOrderBill.aggregate({
        where: { status: { not: "cancelled" } },
        _sum: { grandTotal: true },
      }),
      // Retail orders - paid only
      prisma.retailOrderBill.aggregate({
        where: { status: "paid" },
        _sum: { grandTotal: true },
      }),
      prisma.retailOrderBill.count({
        where: { status: { not: "cancelled" } },
      }),
    ]);

    // Extract values from aggregation results
    const totalInvestment = purchaseStats._sum.totalAmount || 0;
    const paidInvestment = purchaseStats._sum.paidAmount || 0;

    // Calculate stock values (computed fields need JS)
    let stockValue = 0;
    let stockRetailValue = 0;
    let totalStockQuantity = 0;
    for (const product of products) {
      stockValue += product.costPrice * product.stockQuantity;
      stockRetailValue += product.retailPrice * product.stockQuantity;
      totalStockQuantity += product.stockQuantity;
    }

    const wholesaleTotalBusiness = wholesaleTotalStats._sum.grandTotal || 0;
    const wholesalePaidBusiness = wholesalePaidStats._sum.grandTotal || 0;

    const resellerTotalBusiness = resellerTotalStats._sum.grandTotal || 0;
    const resellerPaidBusiness = resellerPaidStats._sum.grandTotal || 0;

    const retailTotalBusiness = retailTotalStats._sum.grandTotal || 0;
    const retailPaidBusiness = retailPaidStats._sum.grandTotal || 0;

    const totalSales = wholesaleTotalBusiness + resellerTotalBusiness + retailTotalBusiness;

    return NextResponse.json({
      wholesaler: {
        totalBusiness: wholesaleTotalBusiness,
        paidBusiness: wholesalePaidBusiness,
        orderCount: wholesaleOrderCount,
      },
      reseller: {
        totalBusiness: resellerTotalBusiness,
        paidBusiness: resellerPaidBusiness,
        orderCount: resellerOrderCount,
      },
      retail: {
        totalBusiness: retailTotalBusiness,
        paidBusiness: retailPaidBusiness,
        orderCount: retailOrderCount,
      },
      grandTotal: totalSales,
      investment: {
        total: totalInvestment,
        paid: paidInvestment,
        pending: totalInvestment - paidInvestment,
        billCount: purchaseBillCount,
      },
      stock: {
        costValue: stockValue,
        retailValue: stockRetailValue,
        quantity: totalStockQuantity,
        potentialProfit: stockRetailValue - stockValue,
      },
      totalSales,
    }, {
      headers: {
        'Cache-Control': 'private, max-age=30, stale-while-revalidate=60',
      },
    });
  } catch (error) {
    console.error("Error fetching business totals:", error);
    return NextResponse.json(
      { error: "Failed to fetch business totals" },
      { status: 500 }
    );
  }
}
